name: "build"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "zulu"
        cache: sbt
    - name: Build
      shell: bash
      run: sbt -v +assembly
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: "$GITHUB_WORKSPACE/target/scala-2.13/diary-generator.jar"
        name: "diary-generator.jar"

# -- memo --
#
# Environment variables - GitHub Docs : https://docs.github.com/ja/actions/learn-github-actions/environment-variables
# $GITHUB_WORKSPACE
# The default working directory on the runner for steps, and the default location of your repository when using the checkout action.
# For example, /home/runner/work/my-repo-name/my-repo-name.
