name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
          cache: sbt
      - name: Build
        shell: bash
        run: sbt -v +assembly
      - name: Create Release Draft
        id: create_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/target/scala-2.13/diary-generator.jar
          name: "diary-generator.jar" # TODO バージョン名をファイル名に含める
