name: Release Drafter

on:
  pull_request:
    branches:
      - main
      - test
    types:
      - closed

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: go get .
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o diary-generator.exe .
      - name: Build for MacOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -o diary-generator-intel .
      - name: Build for MacOS (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -o diary-generator-apple-silicon .
      # TODO Linux
      - name: Create Release Draft
        id: create_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Asset for Windows
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator.exe
          asset_name: "diary-generator.exe"
          asset_content_type: application/octet-stream
          overwrite: true # すでに存在する場合は上書き
      - name: Upload Asset for MacOS (Intel)
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator-intel
          asset_name: "diary-generator-intel"
          asset_content_type: application/octet-stream
          overwrite: true # すでに存在する場合は上書き
      - name: Upload Asset for MacOS (Apple Silicon)
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator-apple-silicon
          asset_name: "diary-generator-apple-silicon"
          asset_content_type: application/octet-stream
          overwrite: true # すでに存在する場合は上書き
