name: Release Drafter

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: go get .
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o diary-generator_windows_amd64/diary-generator.exe diary-generator .
      - name: Copy Batch File
        run: |
          cp bin/archive.bat diary-generator_windows_amd64/archive.bat
          cp bin/init.bat diary-generator_windows_amd64/init.bat
      - name: Build for MacOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -o diary-generator_darwin_amd64/diary-generator diary-generator .
      - name: Copy Shell Script (Intel)
        run: |
          cp bin/archive.sh diary-generator_darwin_amd64/archive.sh
          cp bin/init.sh diary-generator_darwin_amd64/init.sh
      - name: Build for MacOS (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -o diary-generator_darwin_arm64/diary-generator diary-generator .
      - name: Copy Shell Script (Apple Silicon)
        run: |
          cp bin/archive.sh diary-generator_darwin_arm64/archive.sh
          cp bin/init.sh diary-generator_darwin_arm64/init.sh
      - name: Create Release Draft
        id: create_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip Assets
        run: |
          zip -r diary-generator_windows_amd64.zip diary-generator_windows_amd64
          zip -r diary-generator_darwin_amd64.zip diary-generator_darwin_amd64
          zip -r diary-generator_darwin_arm64.zip diary-generator_darwin_arm64
      - name: Upload Asset for Windows
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator_windows_amd64.zip
          asset_name: "diary-generator_windows_amd64.zip"
          overwrite: true # すでに存在する場合は上書き
          asset_content_type: application/zip
      - name: Upload Asset for MacOS (Intel)
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator_darwin_amd64.zip
          asset_name: "diary-generator_darwin_amd64.zip"
          overwrite: true # すでに存在する場合は上書き
          asset_content_type: application/zip
      - name: Upload Asset for MacOS (Apple Silicon)
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/diary-generator_darwin_arm64.zip
          asset_name: "diary-generator_darwin_arm64.zip"
          overwrite: true # すでに存在する場合は上書き
