name: Release Drafter

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: go get .
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o diary-generator.exe .
      # TODO Linux macOS (intel and arm)
      # - name: Create Release Draft
      #   id: create_release_draft
      #   uses: release-drafter/release-drafter@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload Assets
      #   uses: shogo82148/actions-upload-release-asset@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
      #     asset_path: ${{ github.workspace }}/target/scala-2.13/diary-generator.jar
      #     asset_name: "diary-generator.jar" # TODO バージョン名をファイル名に含める
      #     asset_content_type: application/java-archive
      #     overwrite: true # すでに存在する場合は上書き
